"use client";
import {useEffect,useRef} from "react";
import {Renderer,Program,Triangle,Mesh} from "ogl";
import "./RippleGrid.css";
type Props={gridColor?:string;rippleIntensity?:number;gridSize?:number;gridThickness?:number;fadeDistance?:number;vignetteStrength?:number;glowIntensity?:number;opacity?:number;mouseInteraction?:boolean;mouseInteractionRadius?:number};
export default function RippleGrid({gridColor="#adff43",rippleIntensity=.045,gridSize=10,gridThickness=15,fadeDistance=1.5,vignetteStrength=2,glowIntensity=.12,opacity=.65,mouseInteraction=true,mouseInteractionRadius=1.2}:Props){
 const ref=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(!ref.current)return; const el=ref.current; const hex=(h:string)=>{const m=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h);return m?[parseInt(m[1],16)/255,parseInt(m[2],16)/255,parseInt(m[3],16)/255]:[1,1,1]};
 const renderer=new Renderer({dpr:Math.min(devicePixelRatio,2),alpha:true});const gl=renderer.gl;gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);Object.assign(gl.canvas.style,{width:"100%",height:"100%"});el.appendChild(gl.canvas);
 const vert=`attribute vec2 position;varying vec2 vUv;void main(){vUv=position*.5+.5;gl_Position=vec4(position,0.,1.);}`;
 const frag=`precision highp float;uniform float iTime;uniform vec2 iResolution;uniform vec3 gridColor;uniform float rippleIntensity,gridSize,gridThickness,fadeDistance,vignetteStrength,glowIntensity,opacity;uniform vec2 mousePosition;uniform float mouseInfluence,mouseInteractionRadius;varying vec2 vUv;float pi=3.141592;void main(){vec2 uv=vUv*2.-1.;uv.x*=iResolution.x/iResolution.y;float dist=length(uv);float func=sin(pi*(iTime-dist));vec2 r=uv+uv*func*rippleIntensity;vec2 mu=(mousePosition*2.-1.);mu.x*=iResolution.x/iResolution.y;float md=length(uv-mu);float inf=mouseInfluence*exp(-md*md/(mouseInteractionRadius*mouseInteractionRadius));float mw=sin(pi*(iTime*2.-md*3.))*inf;r+=normalize(uv-mu)*mw*rippleIntensity*.3;vec2 a=sin(gridSize*.5*pi*r-pi/2.);vec2 b=abs(a);vec2 s=vec2(smoothstep(0.,.5,b.x),smoothstep(0.,.5,b.y));vec3 c=vec3(0.);c+=exp(-gridThickness*s.x*(.8+.5*sin(pi*iTime)));c+=exp(-gridThickness*s.y);c+=glowIntensity*exp(-gridThickness*.5*s.x)+glowIntensity*exp(-gridThickness*.5*s.y);float d=exp(-2.*clamp(pow(dist,fadeDistance),0.,1.));vec2 vc=vUv-.5;float v=clamp(1.-pow(length(vc)*2.,vignetteStrength),0.,1.);float f=d*v;float alpha=length(c)*f*opacity;gl_FragColor=vec4(c*gridColor*f*opacity,alpha);}`;
 const mouse={x:.5,y:.5},target={x:.5,y:.5};let influence=0;
 const uniforms:any={iTime:{value:0},iResolution:{value:[1,1]},gridColor:{value:hex(gridColor)},rippleIntensity:{value:rippleIntensity},gridSize:{value:gridSize},gridThickness:{value:gridThickness},fadeDistance:{value:fadeDistance},vignetteStrength:{value:vignetteStrength},glowIntensity:{value:glowIntensity},opacity:{value:opacity},mousePosition:{value:[.5,.5]},mouseInfluence:{value:0},mouseInteractionRadius:{value:mouseInteractionRadius}};
 const geometry=new Triangle(gl),program=new Program(gl,{vertex:vert,fragment:frag,uniforms}),mesh=new Mesh(gl,{geometry,program});
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);uniforms.iResolution.value=[el.clientWidth,el.clientHeight]}; const move=(e:MouseEvent)=>{if(!mouseInteraction)return;const r=el.getBoundingClientRect();target.x=(e.clientX-r.left)/r.width;target.y=1-(e.clientY-r.top)/r.height}; const enter=()=>influence=1, leave=()=>influence=0; addEventListener("resize",resize);el.addEventListener("mousemove",move);el.addEventListener("mouseenter",enter);el.addEventListener("mouseleave",leave);resize();
 let id=0;const render=(t:number)=>{uniforms.iTime.value=t*.001;mouse.x+=(target.x-mouse.x)*.1;mouse.y+=(target.y-mouse.y)*.1;uniforms.mouseInfluence.value+=(influence-uniforms.mouseInfluence.value)*.05;uniforms.mousePosition.value=[mouse.x,mouse.y];renderer.render({scene:mesh});id=requestAnimationFrame(render)};id=requestAnimationFrame(render);
 return()=>{cancelAnimationFrame(id);removeEventListener("resize",resize);el.removeEventListener("mousemove",move);el.removeEventListener("mouseenter",enter);el.removeEventListener("mouseleave",leave);gl.getExtension("WEBGL_lose_context")?.loseContext();if(el.contains(gl.canvas))el.removeChild(gl.canvas)}},[]);
 return <div ref={ref} className="ripple-grid-container"/>;
}